@startuml 

top to bottom direction

(Export Data)

(Download Census Data for State) --> (Move & Unzip Census Crosswalk)
(Move & Unzip Census Crosswalk) --> (Create Census Crosswalk)
(Create Census Crosswalk) --> (Merge Census & HMDA)

(Download HMDA Data) --> (Move & Unzip HMDA Data)
(Move & Unzip HMDA Data) --> (Subset HMDA Data to State)
(Subset HMDA Data to State) --> (Merge Census & HMDA)

(Download Zillow Data for State) --> (Move & Unzip Zillow Data)
(Move & Unzip Zillow Data) ---> (Merge Zillow Asmt & Trans)
(Merge Zillow Asmt & Trans) --> (Merge Zillow with HMDA & Census Crosswalk)
(Merge Census & HMDA) --> (Merge Zillow with HMDA & Census Crosswalk)
(Merge Zillow with HMDA & Census Crosswalk) --> (Export Data)

@enduml

